services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    container_name: frontend-transcendence
    env_file:
      - .env
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${WEBSOCKETS_PORT}:${WEBSOCKETS_PORT}"
    container_name: backend-transcendence
    env_file:
      - .env
      - .env.private
    restart: unless-stopped

  database:
    image: postgres:14
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    container_name: ${DATABASE_HOST}
    env_file:
      - .env
      - .env.private
    restart: unless-stopped
